import { css } from "@emotion/core";

// FLEX Properties
const Flex = (props) =>
  css({
    flexDirection: props.X
      ? "row"
      : props.Xr
      ? "row-reverse"
      : props.Y
      ? "column"
      : props.Yr
      ? "column-reverse"
      : "",
    justifyContent: props.Jcs
      ? "flex-start"
      : props.Jcc
      ? "center"
      : props.Jce
      ? "flex-end"
      : props.Jcb
      ? "space-between"
      : props.Jca
      ? "space-Xs"
      : props.Js
      ? "flex-start"
      : props.Jc
      ? "center"
      : props.Je
      ? "flex-end"
      : props.Jb
      ? "space-between"
      : props.Ja
      ? "space-Xs"
      : "",
    alignContent: props.Acs
      ? "flex-start"
      : props.Acc
      ? "center"
      : props.Ace
      ? "flex-end"
      : props.Acb
      ? "space-between"
      : props.Aca
      ? "space-Xs"
      : props.As
      ? "flex-start"
      : props.Ac
      ? "center"
      : props.Ae
      ? "flex-end"
      : props.Ab
      ? "space-between"
      : props.Aa
      ? "space-Xs"
      : "",
    justifyItems: props.Jis
      ? "flex-start"
      : props.Jic
      ? "center"
      : props.Jie
      ? "flex-end"
      : props.Jib
      ? "space-between"
      : props.Jia
      ? "space-Xs"
      : props.Js
      ? "flex-start"
      : props.Jc
      ? "center"
      : props.Je
      ? "flex-end"
      : props.Jb
      ? "space-between"
      : props.Ja
      ? "space-Xs"
      : "",
    alignItems: props.Ais
      ? "flex-start"
      : props.Aic
      ? "center"
      : props.Aie
      ? "flex-end"
      : props.Aib
      ? "space-between"
      : props.Aia
      ? "space-Xs"
      : props.As
      ? "flex-start"
      : props.Ac
      ? "center"
      : props.Ae
      ? "flex-end"
      : props.Ab
      ? "space-between"
      : props.Aa
      ? "space-Xs"
      : "",
  });

export default Flex;
